# Change these first
owner: eyerate # Your GitHub organization or username, where this repository lives
repo: statusPage # The name of this repository

sites:
  - name: Landing Page
    url: https://eyeratebusiness.com/
  - name: Eyerate Reviews
    url: https://eyeratereviews.com/
  - name: Employee App
    url: https://eyeratepeople.com/
  - name: API
    url: https://api.eyeratebusiness.com/v1/api-docs/
  - name: Internal Support App
    url: https://my.eyerate.tech

status-website:
  # cname: eyerate.github.io/statusPage
  baseUrl: /statusPage
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Eyerate Status Page
  navbar:
    - title: Status
      href: /statusPage


runner: [self-hosted]

user-agent: eyerate-service

robotsText: "User-agent: * \n Disallow: /"
