# Change these first
owner: eyerate # Your GitHub organization or username, where this repository lives
repo: statusPage # The name of this repository

sites:
  - name: Landing Page
    url: $URL_LANDING_PAGE
  - name: Eyerate Reviews
    url: $URL_EYERATEREVIEWS
  - name: Employee App
    url: $URL_EMPLOYEEAPP
  - name: API
    url: $URL_API
  - name: Internal Support App
    url: $URL_INTERNAL_SUPPORT_APP
  - name: Employee App Development
    url: $URL_EMPLOYEEAPP_DEV
  - name: Employee App Development Backend
    url: $URL_EMPLOYEEAPP_DEV_BACKEND
    expectedStatusCodes:
      - 404

status-website:
  # cname: eyerate.github.io/statusPage
  baseUrl: /statusPage
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Eyerate Status Page
  js: >-
    window.onload = function(){
      var link = document.querySelectorAll("a[href='/statusPage']");
      link[0].innerHTML = "<div id='seconds-counter' onClick='window.location.reload();'> </div><text onClick='window.location.reload();'>Click here to refresh</text>";
      var seconds = 0;
      var el = document.getElementById('seconds-counter');
      function incrementSeconds() { seconds += 1; if(seconds < 90) { el.innerText = "This page is " + seconds + " seconds old"; } else { el.innerText = "This page is " + Math.round(seconds / 60) + " minutes old"; }}
      var cancel = setInterval(incrementSeconds, 1000);
    }
  navbar:
    - title: Status
      href: /statusPage


runner: [self-hosted]

user-agent: eyerate-service

robotsText: "User-agent: * \n Disallow: /"

